import fs from 'node:fs';
import path from 'node:path';
import { GitEngine } from '../git/engine.js';
import { MetadataStore, writeAtomicJson } from '../metadata/store.js';
import { MannostreeConfig } from '../config/schema.js';
import {
  ParallelHandoffPackage,
  VariantComparisonSummary,
  ExitCode,
  MannostreeError,
} from '../types/index.js';
import { ParallelEngine } from './parallel.js';

export class ParallelHandoffEngine {
  constructor(
    public repoRoot: string,
    public config: MannostreeConfig,
    public git: GitEngine,
    public store: MetadataStore,
    public parallelEngine: ParallelEngine
  ) {}

  public async generateParallelHandoff(
    feature: string,
    options: { to?: string; notes?: string; dryRun?: boolean } = {}
  ): Promise<ParallelHandoffPackage> {
    const experiment = await this.store.getExperiment(feature);
    if (!experiment) {
      throw new MannostreeError(
        `Experiment for feature '${feature}' not found in metadata.`,
        ExitCode.USAGE_ERROR
      );
    }

    if (!experiment.winner) {
      throw new MannostreeError(
        `Cannot generate handoff for experiment '${feature}': no winner has been selected yet. Run 'parallel pick ${feature} <winner>' first.`,
        ExitCode.USAGE_ERROR
      );
    }

    const winnerRecord = await this.store.getWorktree(experiment.winner);
    const winnerBranch = winnerRecord
      ? winnerRecord.branch
      : `experiment/${feature}-${experiment.winner.replace(/^[a-z]+-/, '')}`;
    const winnerSha = (await this.git.getHeadCommit(winnerBranch)) || 'unknown';

    // Get comparison scorecard
    const comparison = await this.parallelEngine.compareVariants(feature);
    const scorecard: VariantComparisonSummary[] = comparison.variants.map((v) => ({
      variant_id: v.id,
      branch: v.branch,
      ahead: v.ahead_count,
      behind: v.behind_count,
      files_changed: v.files_changed,
      insertions: v.lines_added,
      deletions: v.lines_removed,
    }));

    // Identify preserved losers
    const preservedLosers: Array<{
      variant_id: string;
      branch: string;
      head_sha: string;
      archived_or_active: 'active' | 'archived';
    }> = [];

    for (const variantId of experiment.variants) {
      if (variantId === experiment.winner) continue;
      const vRecord = await this.store.getWorktree(variantId);
      const vBranch = vRecord
        ? vRecord.branch
        : `experiment/${feature}-${variantId.replace(/^[a-z]+-/, '')}`;
      const vSha = (await this.git.getHeadCommit(vBranch)) || 'unknown';
      preservedLosers.push({
        variant_id: variantId,
        branch: vBranch,
        head_sha: vSha,
        archived_or_active: (vRecord?.status === 'archived' ? 'archived' : 'active') as
          | 'active'
          | 'archived',
      });
    }

    const now = new Date().toISOString();
    const handoffId = `handoff_${feature}_${now.replace(/[-:T]/g, '').slice(0, 14)}`;

    const prSummaryMarkdown = [
      `# Parallel Experiment Handoff: ${feature}`,
      '',
      `**Base Branch**: \`${experiment.base_branch}\`  `,
      `**Selected Winner**: \`${experiment.winner}\` (\`${winnerBranch}\`)  `,
      `**Winner Commit**: \`${winnerSha}\`  `,
      `**Selection Rationale**: ${experiment.selection_reason || 'Highest evaluation score & passing validations'}  `,
      options.to ? `**Handed Off To**: \`${options.to}\`  ` : '',
      options.notes ? `**Notes**: ${options.notes}  ` : '',
      '',
      '## Comparative Scorecard',
      '| Variant | Branch | Ahead | Behind | Files Changed | Lines +/- | Score |',
      '|---|---|---|---|---|---|---|',
      ...scorecard.map(
        (s) =>
          `| \`${s.variant_id}\` | \`${s.branch}\` | ${s.ahead} | ${s.behind} | ${s.files_changed} | +${s.insertions}/-${s.deletions} | ${s.score !== undefined ? `${s.score}%` : 'N/A'} |`
      ),
      '',
      '## Preserved Non-Winning Variants',
      ...(preservedLosers.length > 0
        ? preservedLosers.map(
            (l) =>
              `- \`${l.variant_id}\` on branch \`${l.branch}\` (${l.archived_or_active}) at \`${l.head_sha}\``
          )
        : ['*No other variants recorded.*']),
      '',
      '---',
      '*Generated by Mannostree parallel handoff engine*',
    ]
      .filter((l) => l !== '')
      .join('\n');

    const artifactRelPath = path.join(this.config.artifact_dir_name, 'parallel-handoff.md');
    const handoffPkg: ParallelHandoffPackage = {
      handoff_id: handoffId,
      feature,
      base_branch: experiment.base_branch,
      created_at: now,
      winner: {
        variant_id: experiment.winner,
        branch: winnerBranch,
        head_sha: winnerSha,
        selection_rationale: experiment.selection_reason || 'Selected winner',
      },
      comparison_scorecard: scorecard,
      preserved_losers: preservedLosers,
      pr_summary_markdown: prSummaryMarkdown,
      artifact_path: artifactRelPath,
    };

    if (!options.dryRun) {
      const handoffJsonPath = path.resolve(
        this.repoRoot,
        this.config.metadata_root,
        'experiments',
        `${feature}-handoff.json`
      );
      writeAtomicJson(handoffJsonPath, handoffPkg);

      const winnerPath = winnerRecord
        ? path.resolve(this.repoRoot, winnerRecord.worktree_path)
        : this.repoRoot;
      const taskDir = path.join(winnerPath, this.config.artifact_dir_name);
      if (!fs.existsSync(taskDir)) {
        fs.mkdirSync(taskDir, { recursive: true });
      }
      fs.writeFileSync(path.join(taskDir, 'parallel-handoff.md'), prSummaryMarkdown, 'utf-8');
    }

    return handoffPkg;
  }
}
