import path from 'node:path';
import fs from 'node:fs';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { MannostreeConfig } from '../config/schema.js';
import { GitEngine } from '../git/engine.js';
import { MetadataStore } from '../metadata/store.js';
import {
  ExitCode,
  MannostreeError,
  WorktreeRecord,
  ExperimentRecord,
  ExperimentMatrixReport,
  FleetBatchPublishOptions,
  FleetBatchPublishReport,
} from '../types/index.js';

const execFileAsync = promisify(execFile);

export type GhExecutor = (
  args: string[],
  cwd: string
) => Promise<{ stdout: string; stderr: string }>;

export async function defaultGhExecutor(
  args: string[],
  cwd: string
): Promise<{ stdout: string; stderr: string }> {
  const { stdout, stderr } = await execFileAsync('gh', args, { cwd });
  return { stdout: stdout.trim(), stderr: stderr.trim() };
}

export interface PrOptions {
  title?: string;
  bodyFile?: string;
  draft?: boolean;
  push?: boolean;
  dryRun?: boolean;
}

export interface PrResult {
  mode: 'prepare-only' | 'published';
  title: string;
  body_file: string;
  body: string;
  pr_url?: string | null;
  pr_number?: number | null;
  instructions?: string;
}

export class PublishEngine {
  public ghExecutor: GhExecutor;

  constructor(
    public repoRoot: string,
    public config: MannostreeConfig,
    public git: GitEngine,
    ghExecutor?: GhExecutor
  ) {
    this.ghExecutor = ghExecutor || defaultGhExecutor;
  }

  public assemblePrBody(worktreeFullPath: string, record: WorktreeRecord): string {
    const artifactRoot = path.join(worktreeFullPath, this.config.artifact_dir_name);
    const contractPath = path.join(artifactRoot, 'task-contract.md');
    const resultsPath = path.join(worktreeFullPath, 'RESULTS.md');
    const qualityPath = path.join(artifactRoot, 'quality-gates.md');
    const reviewPath = path.join(artifactRoot, 'review.md');

    const contractContent = fs.existsSync(contractPath)
      ? fs.readFileSync(contractPath, 'utf-8').trim()
      : 'Task contract not provided.';
    const resultsContent = fs.existsSync(resultsPath)
      ? fs.readFileSync(resultsPath, 'utf-8').trim()
      : 'Results not provided.';
    const qualityContent = fs.existsSync(qualityPath)
      ? fs.readFileSync(qualityPath, 'utf-8').trim()
      : 'Quality gates not provided.';
    const reviewContent = fs.existsSync(reviewPath)
      ? fs.readFileSync(reviewPath, 'utf-8').trim()
      : 'Review not provided.';

    return [
      `# Pull Request: ${record.feature_name || record.id}`,
      '',
      '## Overview',
      `Auto-generated PR body compiled from durable task artifacts for worktree \`${record.id}\`.`,
      '',
      '---',
      '',
      '## Task Contract & Scope',
      contractContent,
      '',
      '---',
      '',
      '## Implementation & Results',
      resultsContent,
      '',
      '---',
      '',
      '## Verification & Quality Gates',
      qualityContent,
      '',
      '---',
      '',
      '## Independent Review',
      reviewContent,
      '',
      '---',
      '',
      `_Generated by Mannostree on ${new Date().toISOString()}_`,
    ].join('\n');
  }

  public assembleParallelPrBody(
    experiment: ExperimentRecord,
    winnerRecord: WorktreeRecord,
    allVariants: WorktreeRecord[],
    evalReport?: ExperimentMatrixReport | null
  ): string {
    const winnerPath = winnerRecord.worktree_path;
    const artifactRoot = path.join(winnerPath, this.config.artifact_dir_name);
    const contractPath = path.join(artifactRoot, 'task-contract.md');
    const resultsPath = path.join(winnerPath, 'RESULTS.md');
    const solutionPath = path.join(artifactRoot, 'solution-options.md');
    const qualityPath = path.join(artifactRoot, 'quality-gates.md');

    const contractContent = fs.existsSync(contractPath)
      ? fs.readFileSync(contractPath, 'utf-8').trim()
      : 'Task contract not provided.';
    const resultsContent = fs.existsSync(resultsPath)
      ? fs.readFileSync(resultsPath, 'utf-8').trim()
      : 'Results not provided.';
    const solutionContent = fs.existsSync(solutionPath)
      ? fs.readFileSync(solutionPath, 'utf-8').trim()
      : '';
    const qualityContent = fs.existsSync(qualityPath)
      ? fs.readFileSync(qualityPath, 'utf-8').trim()
      : 'Quality gates passed.';

    const sections: string[] = [
      `# Pull Request: ${experiment.feature} (Winner: ${winnerRecord.variant || winnerRecord.id})`,
      '',
      '## 🏆 Executive Summary',
      `- **Winning Variant**: \`${winnerRecord.id}\` (\`${winnerRecord.branch}\`)`,
      `- **Target Base Branch**: \`${winnerRecord.base_branch}\``,
      `- **Selection Rationale**: ${experiment.selection_reason || 'Explicitly selected winner.'}`,
      `- **Selected At**: ${experiment.selected_at || new Date().toISOString()}`,
      '',
    ];

    if (evalReport && evalReport.variants && evalReport.variants.length > 0) {
      sections.push('## 📊 Multi-Variant Benchmark Comparison Matrix');
      sections.push('');
      sections.push('| Variant | Rank | Composite Score | Tests | Lint | Performance | Churn (+ / -) | Status |');
      sections.push('| :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |');

      for (const v of evalReport.variants) {
        const isWinner = v.worktree_id === winnerRecord.id;
        const name = isWinner ? `**${v.variant_name} (Winner)**` : v.variant_name;
        const tests = `${v.tests_passed}/${v.tests_total}`;
        const lint = v.lint_clean ? '✓ Clean' : '✗ Issues';
        const perf = v.benchmark_ops_sec
          ? `${v.benchmark_ops_sec.toLocaleString()} ops/s`
          : v.benchmark_latency_ms
          ? `${v.benchmark_latency_ms} ms`
          : 'N/A';
        const churn = `+${v.git_diff.insertions} / -${v.git_diff.deletions}`;
        const status = v.compliant ? '✓ Compliant' : '⚠ Non-compliant';
        sections.push(
          `| ${name} | #${v.rank} | ${v.composite_score.toFixed(1)}/100 | ${tests} | ${lint} | ${perf} | ${churn} | ${status} |`
        );
      }

      sections.push('');
      if (evalReport.winning_justification) {
        sections.push(`> **Evaluation Note**: ${evalReport.winning_justification}`);
        sections.push('');
      }
    }

    if (solutionContent) {
      sections.push('## 💡 Architecture & Solution Options');
      sections.push(solutionContent);
      sections.push('');
    }

    sections.push('## 📋 Task Contract & Verification');
    sections.push(contractContent);
    sections.push('');

    sections.push('## 🧪 Quality Gate Evidence');
    sections.push(qualityContent);
    sections.push('');

    sections.push('## 📦 Preserved Reference Variants');
    const losers = allVariants.filter((v) => v.id !== winnerRecord.id);
    if (losers.length === 0) {
      sections.push('_No competing variants._');
    } else {
      sections.push('The following competing variant branches are preserved for design history:');
      for (const loser of losers) {
        sections.push(`- \`${loser.branch}\` (Variant: \`${loser.variant || loser.id}\`)`);
      }
    }
    sections.push('');
    sections.push('---');
    sections.push(`_Generated by Mannostree Parallel Publish Pipeline on ${new Date().toISOString()}_`);

    return sections.join('\n');
  }

  public async publishPr(
    worktreeFullPath: string,
    record: WorktreeRecord,
    options: PrOptions = {}
  ): Promise<PrResult> {
    const {
      title = `feat(${record.feature_name || record.id}): deliver changes`,
      bodyFile,
      draft = this.config.publish?.default_draft ?? true,
      push = false,
      dryRun = false,
    } = options;

    if (!fs.existsSync(worktreeFullPath)) {
      throw new MannostreeError(
        `Worktree path does not exist: ${worktreeFullPath}`,
        ExitCode.USAGE_ERROR
      );
    }

    let prBody: string;
    if (bodyFile) {
      const fullBodyPath = path.resolve(this.repoRoot, bodyFile);
      if (!fs.existsSync(fullBodyPath)) {
        throw new MannostreeError(
          `Specified PR body file not found: ${bodyFile}`,
          ExitCode.USAGE_ERROR
        );
      }
      prBody = fs.readFileSync(fullBodyPath, 'utf-8');
    } else {
      prBody = this.assemblePrBody(worktreeFullPath, record);
    }

    const prBodyRelPath = path.join(this.config.artifact_dir_name, 'pr-body.md');
    const prBodyFullPath = path.join(worktreeFullPath, prBodyRelPath);

    if (!dryRun) {
      const artifactDir = path.dirname(prBodyFullPath);
      if (!fs.existsSync(artifactDir)) {
        fs.mkdirSync(artifactDir, { recursive: true });
      }
      fs.writeFileSync(prBodyFullPath, prBody, 'utf-8');
    }

    if (!push) {
      return {
        mode: 'prepare-only',
        title,
        body_file: prBodyRelPath,
        body: prBody,
        pr_url: null,
        pr_number: null,
        instructions: `PR prepared locally in '${prBodyRelPath}'. To push and open PR on GitHub, run with --push.`,
      };
    }

    // If push is explicitly requested:
    let prUrl: string | null = null;
    let prNumber: number | null = null;

    if (!dryRun) {
      const remote = this.config.publish?.default_remote || 'origin';
      await this.git.exec(['push', '-u', remote, record.branch], worktreeFullPath);

      // Attempt gh CLI PR creation if available
      try {
        const ghArgs = [
          'pr',
          'create',
          '--head',
          record.branch,
          '--base',
          record.base_branch,
          '--title',
          title,
          '--body-file',
          prBodyFullPath,
        ];
        if (draft) {
          ghArgs.push('--draft');
        }

        const ghRes = await this.ghExecutor(ghArgs, worktreeFullPath);
        prUrl = ghRes.stdout.trim();
        const numMatch = prUrl.match(/\/pull\/(\d+)/);
        if (numMatch) {
          prNumber = parseInt(numMatch[1], 10);
        }
      } catch {
        // gh CLI not available or not logged in; push succeeded
      }
    }

    return {
      mode: 'published',
      title,
      body_file: prBodyRelPath,
      body: prBody,
      pr_url: prUrl,
      pr_number: prNumber,
      instructions: prUrl
        ? `PR opened: ${prUrl}`
        : `Branch '${record.branch}' pushed to remote. Create PR using GitHub web UI or 'gh pr create'.`,
    };
  }

  public async batchPublish(
    options: FleetBatchPublishOptions,
    store: MetadataStore,
    fleetEngine?: any
  ): Promise<FleetBatchPublishReport> {
    const {
      selected,
      draft = this.config.publish?.default_draft ?? true,
      push = false,
      targetBase,
      preview = false,
      dryRun = false,
      force = false,
    } = options;

    const allRecords = await store.listWorktrees();
    let candidates: WorktreeRecord[] = [];

    if (selected && selected.length > 0) {
      candidates = allRecords.filter((r) => selected.includes(r.id) || selected.includes(r.branch));
    } else {
      candidates = allRecords.filter(
        (r) =>
          r.status !== 'archived' &&
          r.status !== 'cleaned' &&
          r.lifecycle_state !== 'CLEANED'
      );
    }

    const isPreview = preview || dryRun;
    const items: FleetBatchPublishReport['results'] = [];
    let publishedCount = 0;
    let skippedCount = 0;
    let failedCount = 0;

    for (const rec of candidates) {
      const fullPath = path.resolve(this.repoRoot, rec.worktree_path);

      if (isPreview) {
        items.push({
          worktree_id: rec.id,
          branch: rec.branch,
          status: 'PUBLISHED',
          message: 'Preview only (dry-run)',
        });
        publishedCount++;
        continue;
      }

      if (fs.existsSync(fullPath)) {
        const isDirty = await this.git.isWorktreeDirty(fullPath);
        if (isDirty && !force) {
          items.push({
            worktree_id: rec.id,
            branch: rec.branch,
            status: 'SKIPPED',
            message: 'Uncommitted changes in worktree (use --force to override)',
          });
          skippedCount++;
          continue;
        }
      }

      try {
        const res = await this.publishPr(fullPath, rec, {
          draft,
          push,
          title: `feat(${rec.feature_name || rec.id}): deliver changes`,
        });

        if (fleetEngine && typeof fleetEngine.releaseLease === 'function') {
          try {
            await fleetEngine.releaseLease(rec.id, { force: true });
          } catch {
            // ignore lease release error
          }
        }

        items.push({
          worktree_id: rec.id,
          branch: rec.branch,
          status: 'PUBLISHED',
          pr_url: res.pr_url,
          pr_number: res.pr_number,
        });
        publishedCount++;
      } catch (err: any) {
        items.push({
          worktree_id: rec.id,
          branch: rec.branch,
          status: 'FAILED',
          message: err.message || 'Failed to publish PR',
        });
        failedCount++;
      }
    }

    return {
      timestamp: new Date().toISOString(),
      total_targeted: candidates.length,
      published_count: publishedCount,
      skipped_count: skippedCount,
      failed_count: failedCount,
      results: items,
    };
  }
}

