import path from 'node:path';
import fs from 'node:fs';
import { MannostreeConfig } from '../config/schema.js';
import { GitEngine } from '../git/engine.js';
import {
  ExitCode,
  MannostreeError,
  WorktreeRecord,
} from '../types/index.js';

export interface PrOptions {
  title?: string;
  bodyFile?: string;
  draft?: boolean;
  push?: boolean;
  dryRun?: boolean;
}

export interface PrResult {
  mode: 'prepare-only' | 'published';
  title: string;
  body_file: string;
  body: string;
  pr_url?: string | null;
  pr_number?: number | null;
  instructions?: string;
}

export class PublishEngine {
  constructor(
    public repoRoot: string,
    public config: MannostreeConfig,
    public git: GitEngine
  ) {}

  public assemblePrBody(worktreeFullPath: string, record: WorktreeRecord): string {
    const artifactRoot = path.join(worktreeFullPath, this.config.artifact_dir_name);
    const contractPath = path.join(artifactRoot, 'task-contract.md');
    const resultsPath = path.join(worktreeFullPath, 'RESULTS.md');
    const qualityPath = path.join(artifactRoot, 'quality-gates.md');
    const reviewPath = path.join(artifactRoot, 'review.md');

    const contractContent = fs.existsSync(contractPath)
      ? fs.readFileSync(contractPath, 'utf-8').trim()
      : 'Task contract not provided.';
    const resultsContent = fs.existsSync(resultsPath)
      ? fs.readFileSync(resultsPath, 'utf-8').trim()
      : 'Results not provided.';
    const qualityContent = fs.existsSync(qualityPath)
      ? fs.readFileSync(qualityPath, 'utf-8').trim()
      : 'Quality gates not provided.';
    const reviewContent = fs.existsSync(reviewPath)
      ? fs.readFileSync(reviewPath, 'utf-8').trim()
      : 'Review not provided.';

    return [
      `# Pull Request: ${record.feature_name || record.id}`,
      '',
      '## Overview',
      `Auto-generated PR body compiled from durable task artifacts for worktree \`${record.id}\`.`,
      '',
      '---',
      '',
      '## Task Contract & Scope',
      contractContent,
      '',
      '---',
      '',
      '## Implementation & Results',
      resultsContent,
      '',
      '---',
      '',
      '## Verification & Quality Gates',
      qualityContent,
      '',
      '---',
      '',
      '## Independent Review',
      reviewContent,
      '',
      '---',
      '',
      `_Generated by Mannostree on ${new Date().toISOString()}_`,
    ].join('\n');
  }

  public async publishPr(
    worktreeFullPath: string,
    record: WorktreeRecord,
    options: PrOptions = {}
  ): Promise<PrResult> {
    const {
      title = `feat(${record.feature_name || record.id}): deliver changes`,
      bodyFile,
      draft = this.config.publish?.default_draft ?? true,
      push = false,
      dryRun = false,
    } = options;

    if (!fs.existsSync(worktreeFullPath)) {
      throw new MannostreeError(
        `Worktree path does not exist: ${worktreeFullPath}`,
        ExitCode.USAGE_ERROR
      );
    }

    let prBody: string;
    if (bodyFile) {
      const fullBodyPath = path.resolve(this.repoRoot, bodyFile);
      if (!fs.existsSync(fullBodyPath)) {
        throw new MannostreeError(
          `Specified PR body file not found: ${bodyFile}`,
          ExitCode.USAGE_ERROR
        );
      }
      prBody = fs.readFileSync(fullBodyPath, 'utf-8');
    } else {
      prBody = this.assemblePrBody(worktreeFullPath, record);
    }

    const prBodyRelPath = path.join(this.config.artifact_dir_name, 'pr-body.md');
    const prBodyFullPath = path.join(worktreeFullPath, prBodyRelPath);

    if (!dryRun) {
      const artifactDir = path.dirname(prBodyFullPath);
      if (!fs.existsSync(artifactDir)) {
        fs.mkdirSync(artifactDir, { recursive: true });
      }
      fs.writeFileSync(prBodyFullPath, prBody, 'utf-8');
    }

    if (!push) {
      return {
        mode: 'prepare-only',
        title,
        body_file: prBodyRelPath,
        body: prBody,
        pr_url: null,
        pr_number: null,
        instructions: `PR prepared locally in '${prBodyRelPath}'. To push and open PR on GitHub, run with --push.`,
      };
    }

    // If push is explicitly requested:
    let prUrl: string | null = null;
    let prNumber: number | null = null;

    if (!dryRun) {
      const remote = this.config.publish?.default_remote || 'origin';
      await this.git.exec(['push', '-u', remote, record.branch], worktreeFullPath);

      // Attempt gh CLI PR creation if available
      try {
        const ghArgs = [
          'pr',
          'create',
          '--head',
          record.branch,
          '--base',
          record.base_branch,
          '--title',
          title,
          '--body-file',
          prBodyFullPath,
        ];
        if (draft) {
          ghArgs.push('--draft');
        }

        const ghRes = await this.git.exec(['gh', ...ghArgs], worktreeFullPath);
        prUrl = ghRes.stdout.trim();
        const numMatch = prUrl.match(/\/pull\/(\d+)/);
        if (numMatch) {
          prNumber = parseInt(numMatch[1], 10);
        }
      } catch {
        // gh CLI not available or not logged in; push succeeded
      }
    }

    return {
      mode: 'published',
      title,
      body_file: prBodyRelPath,
      body: prBody,
      pr_url: prUrl,
      pr_number: prNumber,
      instructions: prUrl
        ? `PR opened: ${prUrl}`
        : `Branch '${record.branch}' pushed to remote. Create PR using GitHub web UI or 'gh pr create'.`,
    };
  }
}
